apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: roboshop
  name: roboshop-trainee
rules:
- apiGroups: [""] # "" indicates the core API group i.e v1 generally core API group is considered as v1
  resources: ["pods"] #nouns
  verbs: ["get", "watch", "list"] #actions
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: roboshop
  name: roboshop-junior
rules:
- apiGroups: [""] # "" indicates the core API group i.e v1 generally core API group is considered as v1
  resources: ["pods"] #nouns
  verbs: ["get", "watch", "list"] #actions
- apiGroups: ["apps"] # "" indicates the core API group i.e v1 generally core API group is considered as v1
  resources: ["deployments"] #nouns
  verbs: ["get", "list", "watch", "create", "update", "patch", "delete"] #actions
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: roboshop
  name: roboshop-teamlead
rules:
- apiGroups: ["*"] # All 
  resources: ["*"] #all
  verbs: ["*"] #all
---
apiVersion: rbac.authorization.k8s.io/v1
# This role binding allows "jane" to read pods in the "default" namespace.
# You need to already have a Role named "pod-reader" in that namespace.
kind: RoleBinding
metadata:
  name: suresh
  namespace: roboshop
subjects:
# You can specify more than one "subject"
- kind: User
  name: suresh # "name" is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  # "roleRef" specifies the binding to a Role / ClusterRole
  kind: Role #this must be Role or ClusterRole
  name: roboshop-teamlead # this must match the name of the Role or ClusterRole you wish to bind to
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: roboshop-cluster
rules:
- apiGroups: [""]
  resources: ["persistentvolumes"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
# This cluster role binding allows anyone in the "manager" group to read secrets in any namespace.
kind: ClusterRoleBinding
metadata:
  name: roboshop-cluster
subjects:
- kind: User
  name: suresh # Name is case sensitive
  apiGroup: rbac.authorization.k8s.io
roleRef:
  kind: ClusterRole
  name: roboshop-cluster
  apiGroup: rbac.authorization.k8s.io
