apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  namespace: roboshop
  name: roboshop-trainee
rules:
- apiGroups: [""] # "" indicates the core API group i.e v1 generally core API group is considered as v1
  resources: ["pods"] #nouns
  verbs: ["get", "watch", "list"] #actions